name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    name: Auto approve dependabot pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.BOT_GITHUB_TOKEN }}"
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.BOT_GITHUB_TOKEN }}"
